language: java
jdk: oraclejdk8
cache:
  directories:
    - .autoconf
    - $HOME/.m2
script:
  - mvn clean compile
  - mvn checkstyle:check
  - mvn pmd:check
  - mvn spotbugs:check
  - mvn test
  - mvn install
